const define = (id, title, category, expected, fixture = 'button', mode = 'dom', manual = '') => ({
  id,
  title,
  category,
  description: expected,
  expected,
  fixture,
  mode,
  manual,
  reference: 'https://github.com/WICG/html-in-canvas#accessibility',
  revision: 1,
});
export const cases = [
  define(
    'basic-button',
    'Basic accessible button',
    'Semantics',
    'A native button retains its role, text and activation behavior.',
    'button',
    'dom',
    'Inspect the accessibility tree: role button, name Delete. Activate using Enter and Space.',
  ),
  define(
    'name-propagation',
    'Accessible name propagation',
    'Semantics',
    'Changing button text updates its DOM text and spoken accessible name.',
    'name',
    'dom',
    'Confirm the name changes from Delete to Delete item in DevTools and your screen reader.',
  ),
  define(
    'tab-navigation',
    'Keyboard tab navigation',
    'Keyboard',
    'Tab visits First, Second, Third in order; Shift+Tab reverses the order.',
    'multiple',
    'manual',
    'Tab into the canvas, visit all three buttons, then reverse using Shift+Tab. Record actual focus order.',
  ),
  define(
    'programmatic-focus',
    'Programmatic focus',
    'Focus',
    'Calling focus() makes the drawn button document.activeElement.',
    'button',
    'focus',
  ),
  define(
    'focus-indicator',
    'Visible focus indicator',
    'Focus',
    'A keyboard-focused button has a visible, aligned focus indicator in the canvas.',
    'button',
    'manual',
    'Use Tab to focus Delete. Confirm its white inset focus ring is visible and aligned.',
  ),
  define(
    'transform',
    'Translated and rotated element',
    'Transforms',
    'Raster bounds and DOM bounds agree after translation and rotation.',
    'button',
    'geometry',
  ),
  define(
    'nested-transforms',
    'Nested transforms',
    'Transforms',
    'Composed canvas transforms preserve raster-to-DOM alignment.',
    'button',
    'geometry',
  ),
  define(
    'clipping',
    'Clipped interactive element',
    'Geometry',
    'Only the drawn half is visible; the clipped half must not accept pointer input.',
    'button',
    'manual',
    'Click inside the visible half, then where the clipped half would be. Only the visible half should activate. DOM bounding boxes need not shrink with clipping.',
  ),
  define(
    'hidden-content',
    'Hidden content',
    'Semantics',
    'A hidden button has no layout box and is excluded from navigation and accessibility.',
    'hidden',
    'dom',
    'Verify Hidden action is absent from the accessibility tree and skipped by Tab.',
  ),
  define(
    'aria-label',
    'ARIA label',
    'ARIA',
    'The visible × control exposes Close dialog as its accessible name.',
    'label',
    'dom',
    'Inspect the computed accessibility name and confirm your screen reader announces Close dialog.',
  ),
  define(
    'aria-relationships',
    'ARIA relationships',
    'ARIA',
    'aria-labelledby and aria-describedby resolve to the intended text.',
    'relationships',
    'dom',
    'Confirm name Delete item and description This cannot be undone in the accessibility tree.',
  ),
  define(
    'multiple-elements',
    'Multiple interactive elements',
    'Keyboard',
    'Three distinct controls remain independently focusable and clickable.',
    'multiple',
    'dom',
    'Click each control and verify the activation count, then navigate them with Tab.',
  ),
  define(
    'geometry-sync',
    'Geometry synchronization',
    'Geometry',
    'Independently sampled raster pixels and DOM border-box bounds agree within 2 CSS pixels.',
    'button',
    'geometry',
  ),
  define(
    'dynamic-geometry',
    'Dynamic geometry changes',
    'Geometry',
    'After a redraw at a new position, raster and DOM bounds remain aligned.',
    'button',
    'geometry',
  ),
  define(
    'rtl',
    'RTL content',
    'Semantics',
    'Arabic text retains RTL direction and a meaningful reading order.',
    'rtl',
    'dom',
    'Read the Arabic button with a compatible screen reader. Verify direction and pronunciation.',
  ),
  define(
    'nested-drawable',
    'Nested drawable elements',
    'Transforms',
    'A nested drawable child is painted separately and remains interactive.',
    'nested',
    'manual',
    'Confirm both the parent panel and child Delete button are painted. Focus and activate the child.',
  ),
  define(
    'focus-after-animation',
    'Focus after animation',
    'Focus',
    'After the animation ends, focus remains on the moved button and geometry is synchronized.',
    'button',
    'animation',
    'Confirm the focus indicator follows the button throughout the animation.',
  ),
  define(
    'element-removal',
    'Element removal',
    'Semantics',
    'Removing a drawn control removes its DOM connection and stale canvas pixels on repaint.',
    'button',
    'removal',
    'Confirm the removed control is absent from the accessibility tree and Tab order.',
  ),
  define(
    'disabled-control',
    'Disabled interactive controls',
    'Keyboard',
    'A disabled native button rejects programmatic focus and click activation.',
    'disabled',
    'disabled',
    'Verify it is skipped by Tab and announced as disabled in a screen reader.',
  ),
  define(
    'semantic-structure',
    'Screen-reader semantic structure',
    'Semantics',
    'Heading, list and button semantics remain navigable inside canvas.',
    'structure',
    'manual',
    'Use heading/list navigation in your screen reader. Expect Actions, two list items, and Delete.',
  ),
];
